packages:
  - .

allowBuilds:
  '@biomejs/biome': true
  '@scarf/scarf': false
  dtrace-provider: false
  esbuild: true
  keccak: false

patchedDependencies:
  "@balmy/sdk@0.9.0": patches/@balmy__sdk@0.9.0.patch
